make cachehome configurable
blmayer/astro pull request #12
Opened 2021-12-17 16:04 UTC by guzzisti

Hi!
Not sure if this is anything you'd consider but here we go:
"cachehome" folder is now configurable via `astro.conf`

My main use case:
`astro` makes heavy use of files (for history and links within pages), which are stored inside `[cachehome]/astro/`. I want the cachehome to be configurable to move these working files to a memory-backed folder (e.g. via `tmpfs`).

2021-12-17 22:58 UTC, blmayer requested changes

2021-12-17 22:58 UTC, blmayer commented on README.md
> +hints:
```suggestion
**hints:**
```

2021-12-17 22:58 UTC, blmayer commented on README.md
> +hints:
I think it deserves a highlight.

2021-12-17 22:58 UTC, blmayer commented on astro
> +		[ -f "$linkfile" ] && rm "$linkfile"
I think is better to call it `linksfile` instead of `linkfile` as the file is *$cachedir/links*.

2021-12-17 22:59 UTC, blmayer commented
Hi guzzisti.

Nice idea, I just want you to adjust some little things before I approve your PR.

2021-12-18 08:57 UTC, guzzisti commented
I might annoy you with more PRs in the next days. ;)

2021-12-19 15:50 UTC, blmayer commented
> 

That will be great.

2021-12-19 15:51 UTC, blmayer approved these changes

2021-12-19 15:52 UTC, merged

2021-12-19 15:52 UTC, blmayer commented
Merged, thanks again.