explain astro.conf in README.md
blmayer/astro pull request #8
Opened 2021-12-10 18:20 UTC by guzzisti

Not sure if you are interested in PRs at all. I'll send that along anyway. :)

When playing around with astro i realized it supports customization via a config file, but this wasn't mentioned anywhere.
I added a few words in the README.md explaining the config format.

2021-12-10 20:03 UTC, blmayer requested changes

2021-12-10 20:03 UTC, blmayer commented on README.md
> +homepage=gmn.clttr.info
```suggestion
homepage=gemini.circumlunar.space
```

2021-12-10 20:03 UTC, blmayer commented
Hi guzzisti, thanks for taking your time, and yes, contributions are welcome.

That is a nice catch, I didn't notice this missing part, but just one small change before I accept your PR:

Please change the homepage setting to the default value I've been using (*gemini.circumlunar.space*), since I think is a more "neutral" website. I added the suggestion to the commit for your your convenience.

And thanks again!

2021-12-11 07:40 UTC, guzzisti commented
lol, sorry, this wasn't meant to be there

2021-12-11 17:00 UTC, blmayer approved these changes

2021-12-11 17:01 UTC, merged

2021-12-11 17:02 UTC, blmayer commented
It's merged! Thank you for contributing.